-- 1.5 Exercise 5
-- Problem statement: For each IP in the top 100 list previously computed, find the number of bytes uploaded by the
-- largest TCP connection and the percentage of the bytes uploaded by this connection over the total number of uploaded
-- bytes.
-- Hint: for this exercise, you need to join two datasets: the output of the previous exercise with the original tstat dataset.
-- Questions: 1. How many jobs were generated? 2. Describe how the join is executed.