-- 1.8 Exercise 8
-- Problem statement: calculate the percentage of bytes received by each distinct server port over the total number of
-- bytes received by all the server ports.
-- Questions: 1. How many reducers were launched? Which degree of parallelism did you choose? Why? 2. If you run the
-- exercise on a large cluster, using the same dataset, would you use a different value of parallelism?